/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StoriesRouteImport } from './routes/stories'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiWhatsappProxyRouteImport } from './routes/api/whatsapp-proxy'
import { Route as ApiSearchImageRouteImport } from './routes/api/search-image'
import { Route as ApiQuotationsRouteImport } from './routes/api/quotations'
import { Route as ApiPlacesLeadsRouteImport } from './routes/api/places-leads'
import { Route as ApiLocalLeadsRouteImport } from './routes/api/local-leads'
import { Route as ApiKeysStatusRouteImport } from './routes/api/keys-status'
import { Route as Api3dTrendsRouteImport } from './routes/api/3d-trends'
import { Route as ApiTelegramSendStlRouteImport } from './routes/api/telegram/send-stl'
import { Route as ApiSerpapiStatusRouteImport } from './routes/api/serpapi.status'

const StoriesRoute = StoriesRouteImport.update({
  id: '/stories',
  path: '/stories',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWhatsappProxyRoute = ApiWhatsappProxyRouteImport.update({
  id: '/api/whatsapp-proxy',
  path: '/api/whatsapp-proxy',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSearchImageRoute = ApiSearchImageRouteImport.update({
  id: '/api/search-image',
  path: '/api/search-image',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiQuotationsRoute = ApiQuotationsRouteImport.update({
  id: '/api/quotations',
  path: '/api/quotations',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPlacesLeadsRoute = ApiPlacesLeadsRouteImport.update({
  id: '/api/places-leads',
  path: '/api/places-leads',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLocalLeadsRoute = ApiLocalLeadsRouteImport.update({
  id: '/api/local-leads',
  path: '/api/local-leads',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiKeysStatusRoute = ApiKeysStatusRouteImport.update({
  id: '/api/keys-status',
  path: '/api/keys-status',
  getParentRoute: () => rootRouteImport,
} as any)
const Api3dTrendsRoute = Api3dTrendsRouteImport.update({
  id: '/api/3d-trends',
  path: '/api/3d-trends',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTelegramSendStlRoute = ApiTelegramSendStlRouteImport.update({
  id: '/api/telegram/send-stl',
  path: '/api/telegram/send-stl',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSerpapiStatusRoute = ApiSerpapiStatusRouteImport.update({
  id: '/api/serpapi/status',
  path: '/api/serpapi/status',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/stories': typeof StoriesRoute
  '/api/3d-trends': typeof Api3dTrendsRoute
  '/api/keys-status': typeof ApiKeysStatusRoute
  '/api/local-leads': typeof ApiLocalLeadsRoute
  '/api/places-leads': typeof ApiPlacesLeadsRoute
  '/api/quotations': typeof ApiQuotationsRoute
  '/api/search-image': typeof ApiSearchImageRoute
  '/api/whatsapp-proxy': typeof ApiWhatsappProxyRoute
  '/api/serpapi/status': typeof ApiSerpapiStatusRoute
  '/api/telegram/send-stl': typeof ApiTelegramSendStlRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/stories': typeof StoriesRoute
  '/api/3d-trends': typeof Api3dTrendsRoute
  '/api/keys-status': typeof ApiKeysStatusRoute
  '/api/local-leads': typeof ApiLocalLeadsRoute
  '/api/places-leads': typeof ApiPlacesLeadsRoute
  '/api/quotations': typeof ApiQuotationsRoute
  '/api/search-image': typeof ApiSearchImageRoute
  '/api/whatsapp-proxy': typeof ApiWhatsappProxyRoute
  '/api/serpapi/status': typeof ApiSerpapiStatusRoute
  '/api/telegram/send-stl': typeof ApiTelegramSendStlRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/stories': typeof StoriesRoute
  '/api/3d-trends': typeof Api3dTrendsRoute
  '/api/keys-status': typeof ApiKeysStatusRoute
  '/api/local-leads': typeof ApiLocalLeadsRoute
  '/api/places-leads': typeof ApiPlacesLeadsRoute
  '/api/quotations': typeof ApiQuotationsRoute
  '/api/search-image': typeof ApiSearchImageRoute
  '/api/whatsapp-proxy': typeof ApiWhatsappProxyRoute
  '/api/serpapi/status': typeof ApiSerpapiStatusRoute
  '/api/telegram/send-stl': typeof ApiTelegramSendStlRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/stories'
    | '/api/3d-trends'
    | '/api/keys-status'
    | '/api/local-leads'
    | '/api/places-leads'
    | '/api/quotations'
    | '/api/search-image'
    | '/api/whatsapp-proxy'
    | '/api/serpapi/status'
    | '/api/telegram/send-stl'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/stories'
    | '/api/3d-trends'
    | '/api/keys-status'
    | '/api/local-leads'
    | '/api/places-leads'
    | '/api/quotations'
    | '/api/search-image'
    | '/api/whatsapp-proxy'
    | '/api/serpapi/status'
    | '/api/telegram/send-stl'
  id:
    | '__root__'
    | '/'
    | '/stories'
    | '/api/3d-trends'
    | '/api/keys-status'
    | '/api/local-leads'
    | '/api/places-leads'
    | '/api/quotations'
    | '/api/search-image'
    | '/api/whatsapp-proxy'
    | '/api/serpapi/status'
    | '/api/telegram/send-stl'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  StoriesRoute: typeof StoriesRoute
  Api3dTrendsRoute: typeof Api3dTrendsRoute
  ApiKeysStatusRoute: typeof ApiKeysStatusRoute
  ApiLocalLeadsRoute: typeof ApiLocalLeadsRoute
  ApiPlacesLeadsRoute: typeof ApiPlacesLeadsRoute
  ApiQuotationsRoute: typeof ApiQuotationsRoute
  ApiSearchImageRoute: typeof ApiSearchImageRoute
  ApiWhatsappProxyRoute: typeof ApiWhatsappProxyRoute
  ApiSerpapiStatusRoute: typeof ApiSerpapiStatusRoute
  ApiTelegramSendStlRoute: typeof ApiTelegramSendStlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stories': {
      id: '/stories'
      path: '/stories'
      fullPath: '/stories'
      preLoaderRoute: typeof StoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/whatsapp-proxy': {
      id: '/api/whatsapp-proxy'
      path: '/api/whatsapp-proxy'
      fullPath: '/api/whatsapp-proxy'
      preLoaderRoute: typeof ApiWhatsappProxyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/search-image': {
      id: '/api/search-image'
      path: '/api/search-image'
      fullPath: '/api/search-image'
      preLoaderRoute: typeof ApiSearchImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/quotations': {
      id: '/api/quotations'
      path: '/api/quotations'
      fullPath: '/api/quotations'
      preLoaderRoute: typeof ApiQuotationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/places-leads': {
      id: '/api/places-leads'
      path: '/api/places-leads'
      fullPath: '/api/places-leads'
      preLoaderRoute: typeof ApiPlacesLeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/local-leads': {
      id: '/api/local-leads'
      path: '/api/local-leads'
      fullPath: '/api/local-leads'
      preLoaderRoute: typeof ApiLocalLeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/keys-status': {
      id: '/api/keys-status'
      path: '/api/keys-status'
      fullPath: '/api/keys-status'
      preLoaderRoute: typeof ApiKeysStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/3d-trends': {
      id: '/api/3d-trends'
      path: '/api/3d-trends'
      fullPath: '/api/3d-trends'
      preLoaderRoute: typeof Api3dTrendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/telegram/send-stl': {
      id: '/api/telegram/send-stl'
      path: '/api/telegram/send-stl'
      fullPath: '/api/telegram/send-stl'
      preLoaderRoute: typeof ApiTelegramSendStlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/serpapi/status': {
      id: '/api/serpapi/status'
      path: '/api/serpapi/status'
      fullPath: '/api/serpapi/status'
      preLoaderRoute: typeof ApiSerpapiStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  StoriesRoute: StoriesRoute,
  Api3dTrendsRoute: Api3dTrendsRoute,
  ApiKeysStatusRoute: ApiKeysStatusRoute,
  ApiLocalLeadsRoute: ApiLocalLeadsRoute,
  ApiPlacesLeadsRoute: ApiPlacesLeadsRoute,
  ApiQuotationsRoute: ApiQuotationsRoute,
  ApiSearchImageRoute: ApiSearchImageRoute,
  ApiWhatsappProxyRoute: ApiWhatsappProxyRoute,
  ApiSerpapiStatusRoute: ApiSerpapiStatusRoute,
  ApiTelegramSendStlRoute: ApiTelegramSendStlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
